import numpy as np
import pandas as pd
from typing import Dict
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error,
    r2_score,
)


def calc_metrics(y_true: pd.Series, y_pred: np.ndarray) -> Dict[str, float]:
    """
    Calculate evaluation metrics for the forecasting model.

    Metrics calculated:
    - Mean Absolute Error (MAE)
    - Root Mean Squared Error (RMSE)
    - R-squared (R2)
    - Mean Absolute Percentage Error (MAPE) — FIX: was missing, now included.

    Parameters
    ----------
    y_true : pd.Series
        Actual observed values.
    y_pred : np.ndarray
        Predicted values generated by the model.

    Returns
    -------
    Dict[str, float]
        Dictionary containing MAE, RMSE, R2, and MAPE.
    """

    mae = mean_absolute_error(y_true, y_pred)

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    r2 = r2_score(y_true, y_pred)

    # FIX: MAPE was not computed here before, so it always defaulted to 0 in
    # app.py. It is now calculated and returned alongside the other metrics.
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100

    return {
        "MAE": float(mae),
        "RMSE": float(rmse),
        "R2": float(r2),
        "MAPE": round(float(mape), 2),
    }